[package]
org = "wso2"
name = "list_files_and_folders"
version = "0.1.0"
distribution = "2201.10.2"

[[dependency]]
org = "ballerinax"
name = "dropbox"
version = "0.1.0"

[build-options]
observabilityIncluded = true
