[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "dropbox"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Content & Files/File Management & Storage", "Cost/Free"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-dropbox"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
